move to parboiled-java version 1.1.7 to fix Pegdown Custom ParserPlugin binding failed
java.lang.RuntimeException: Error creating extended parser class: null